### ISSUE TITLE
Add or remove columns?

### ISSUE THREAD

**Issue by chronicom** [edisonneza/jspdf-invoice-template#4]
Hi, thank you for the great work. I can see that you have defined 6 columns for the table. I am just wondering if there is any easy way to remove the "item number" and "unit" ?  It seems that these 6 columns are hard coded in the index.js file isn't it?

**Comment by D-sandaruwan** [comment]
I have the same issue.

**Comment by edisonneza** [comment]
> Hi, thank you for the great work. I can see that you have defined 6 columns for the table. I am just wondering if there is any easy way to remove the "item number" and "unit" ? It seems that these 6 columns are hard coded in the index.js file isn't it?

Hi, thanks!
Yeah, to be honest, this issue is on my TODO list, but due to limited time available, I haven't implemented it yet. 
I've in mind to support style also, for all the columns. Maybe at the moment, I will implement just the customization for the "width" of the columns, but in the future other styles too. 

Thank you for using it @chronicom, @D-sandaruwan !

**Comment by edisonneza** [comment]
This feature is added now in package [v1.3.1](https://www.npmjs.com/package/jspdf-invoice-template/v/1.3.1). 

I'll close the issue.
