### ISSUE TITLE
Config Table Width

### ISSUE THREAD

**Issue by besnikh** [edisonneza/jspdf-invoice-template#9]
Shqipe thnx for this :) 
I really appreciate what you have done here, that saved me a lot of time!! 

I have 1 question though: 

1. Is it possible to change width of each table since even in your example the # (number) column is taking same space just as Description and in my case I would like to make that width smaller

Looking forward to receive back,
thnx in advance
Cheers

**Comment by edisonneza** [comment]
Hi Besnik, 
   thanks for your appreciation :) 
   
Yeah, your question is right. Actually, this feature is in my TODO list for this package (exactly wrote "Add style for columns (at least width)"), but due to lack of time, it's not been implemented yet. 

Being that this is a must-have feature, I'll do my best to implement and publish the package ASAP. 

Regards!

**Comment by edisonneza** [comment]
Implemented :)
